# Generated by Django 4.0.1 on 2024-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_address_patient_age_patient_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_visit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
