# Generated by Django 4.0.1 on 2024-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='note',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
