# Generated by Django 4.0.1 on 2024-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_patient_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
