# Generated by Django 4.0.1 on 2024-04-26 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_email_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(default=datetime.date(2024, 4, 26), null=True),
        ),
    ]
