# Generated by Django 4.0.1 on 2024-05-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medecine_detail',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_visit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='note',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='visit_date',
        ),
    ]
